import Head from "next/head";
import styles from "../styles/Home.module.css";
import { GetServerSideProps } from "next";

type Props = { nowDate: string; pageTitle: string };

export default function SsrDemo(props: Props) {
  return (
    <div className={styles.container}>
      <Head>
        <title>{props.pageTitle}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h2 className={styles.title}>{props.pageTitle}</h2>
        <p>What time is it now?</p>
        <p>It&apos;s {props.nowDate}.</p>
      </main>
    </div>
  );
}

export const getServerSideProps: GetServerSideProps<Props> = async (
  context
) => {
  return {
    props: {
      nowDate: new Date().toLocaleString(),
      pageTitle: "SSR Demo",
    },
  };
};
